hexcolors = {}
hexcolors	[	1	]	=	"#800000"	--	maroon						
hexcolors	[	2	]	=	"#8B0000"	--	dark red						
hexcolors	[	3	]	=	"#A52A2A"	--	brown						
hexcolors	[	4	]	=	"#B22222"	--	firebrick						
hexcolors	[	5	]	=	"#DC143C"	--	crimson						
hexcolors	[	6	]	=	"#FF0000"	--	red						
hexcolors	[	7	]	=	"#FF6347"	--	tomato						
hexcolors	[	8	]	=	"#FF7F50"	--	coral						
hexcolors	[	9	]	=	"#CD5C5C"	--	indian red						
hexcolors	[	10	]	=	"#F08080"	--	light coral						
hexcolors	[	11	]	=	"#E9967A"	--	dark salmon						
hexcolors	[	12	]	=	"#FA8072"	--	salmon						
hexcolors	[	13	]	=	"#FFA07A"	--	light salmon						
hexcolors	[	14	]	=	"#FF4500"	--	orange red						
hexcolors	[	15	]	=	"#FF8C00"	--	dark orange						
hexcolors	[	16	]	=	"#FFA500"	--	orange						
hexcolors	[	17	]	=	"#FFD700"	--	gold						
hexcolors	[	18	]	=	"#B8860B"	--	dark golden rod						
hexcolors	[	19	]	=	"#DAA520"	--	golden rod						
hexcolors	[	20	]	=	"#EEE8AA"	--	pale golden rod						
hexcolors	[	21	]	=	"#BDB76B"	--	dark khaki						
hexcolors	[	22	]	=	"#F0E68C"	--	khaki						
hexcolors	[	23	]	=	"#808000"	--	olive						
hexcolors	[	24	]	=	"#FFFF00"	--	yellow						
hexcolors	[	25	]	=	"#9ACD32"	--	yellow green						
hexcolors	[	26	]	=	"#556B2F"	--	dark olive green						
hexcolors	[	27	]	=	"#6B8E23"	--	olive drab						
hexcolors	[	28	]	=	"#7CFC00"	--	lawn green						
hexcolors	[	29	]	=	"#7FFF00"	--	chart reuse						
hexcolors	[	30	]	=	"#ADFF2F"	--	green yellow						
hexcolors	[	31	]	=	"#006400"	--	dark green						
hexcolors	[	32	]	=	"#008000"	--	green						
hexcolors	[	33	]	=	"#228B22"	--	forest green						
hexcolors	[	34	]	=	"#00FF00"	--	lime						
hexcolors	[	35	]	=	"#32CD32"	--	lime green						
hexcolors	[	36	]	=	"#90EE90"	--	light green						
hexcolors	[	37	]	=	"#98FB98"	--	pale green						
hexcolors	[	38	]	=	"#8FBC8F"	--	dark sea green						
hexcolors	[	39	]	=	"#00FA9A"	--	medium spring green						
hexcolors	[	40	]	=	"#00FF7F"	--	spring green						
hexcolors	[	41	]	=	"#2E8B57"	--	sea green						
hexcolors	[	42	]	=	"#66CDAA"	--	medium aqua marine						
hexcolors	[	43	]	=	"#3CB371"	--	medium sea green						
hexcolors	[	44	]	=	"#20B2AA"	--	light sea green						
hexcolors	[	45	]	=	"#2F4F4F"	--	dark slate gray						
hexcolors	[	46	]	=	"#008080"	--	teal						
hexcolors	[	47	]	=	"#008B8B"	--	dark cyan						
hexcolors	[	48	]	=	"#00FFFF"	--	aqua						
hexcolors	[	49	]	=	"#00FFFF"	--	cyan						
hexcolors	[	50	]	=	"#E0FFFF"	--	light cyan						
hexcolors	[	51	]	=	"#00CED1"	--	dark turquoise						
hexcolors	[	52	]	=	"#40E0D0"	--	turquoise						
hexcolors	[	53	]	=	"#48D1CC"	--	medium turquoise						
hexcolors	[	54	]	=	"#AFEEEE"	--	pale turquoise						
hexcolors	[	55	]	=	"#7FFFD4"	--	aqua marine						
hexcolors	[	56	]	=	"#B0E0E6"	--	powder blue						
hexcolors	[	57	]	=	"#5F9EA0"	--	cadet blue						
hexcolors	[	58	]	=	"#4682B4"	--	steel blue						
hexcolors	[	59	]	=	"#6495ED"	--	corn flower blue						
hexcolors	[	60	]	=	"#00BFFF"	--	deep sky blue						
hexcolors	[	61	]	=	"#1E90FF"	--	dodger blue						
hexcolors	[	62	]	=	"#ADD8E6"	--	light blue						
hexcolors	[	63	]	=	"#87CEEB"	--	sky blue						
hexcolors	[	64	]	=	"#87CEFA"	--	light sky blue						
hexcolors	[	65	]	=	"#191970"	--	midnight blue						
hexcolors	[	66	]	=	"#000080"	--	navy						
hexcolors	[	67	]	=	"#00008B"	--	dark blue						
hexcolors	[	68	]	=	"#0000CD"	--	medium blue						
hexcolors	[	69	]	=	"#0000FF"	--	blue						
hexcolors	[	70	]	=	"#4169E1"	--	royal blue						
hexcolors	[	71	]	=	"#8A2BE2"	--	blue violet						
hexcolors	[	72	]	=	"#4B0082"	--	indigo						
hexcolors	[	73	]	=	"#483D8B"	--	dark slate blue						
hexcolors	[	74	]	=	"#6A5ACD"	--	slate blue						
hexcolors	[	75	]	=	"#7B68EE"	--	medium slate blue						
hexcolors	[	76	]	=	"#9370DB"	--	medium purple						
hexcolors	[	77	]	=	"#8B008B"	--	dark magenta						
hexcolors	[	78	]	=	"#9400D3"	--	dark violet						
hexcolors	[	79	]	=	"#9932CC"	--	dark orchid						
hexcolors	[	80	]	=	"#BA55D3"	--	medium orchid						
hexcolors	[	81	]	=	"#800080"	--	purple						
hexcolors	[	82	]	=	"#D8BFD8"	--	thistle						
hexcolors	[	83	]	=	"#DDA0DD"	--	plum						
hexcolors	[	84	]	=	"#EE82EE"	--	violet						
hexcolors	[	85	]	=	"#FF00FF"	--	magenta / fuchsia						
hexcolors	[	86	]	=	"#DA70D6"	--	orchid						
hexcolors	[	87	]	=	"#C71585"	--	medium violet red						
hexcolors	[	88	]	=	"#DB7093"	--	pale violet red						
hexcolors	[	89	]	=	"#FF1493"	--	deep pink						
hexcolors	[	90	]	=	"#FF69B4"	--	hot pink						
hexcolors	[	91	]	=	"#FFB6C1"	--	light pink						
hexcolors	[	92	]	=	"#FFC0CB"	--	pink						
hexcolors	[	93	]	=	"#FAEBD7"	--	antique white						
hexcolors	[	94	]	=	"#F5F5DC"	--	beige						
hexcolors	[	95	]	=	"#FFE4C4"	--	bisque						
hexcolors	[	96	]	=	"#FFEBCD"	--	blanched almond						
hexcolors	[	97	]	=	"#F5DEB3"	--	wheat						
hexcolors	[	98	]	=	"#FFF8DC"	--	corn silk						
hexcolors	[	99	]	=	"#FFFACD"	--	lemon chiffon						
hexcolors	[	100	]	=	"#FAFAD2"	--	light golden rod yellow						
hexcolors	[	101	]	=	"#FFFFE0"	--	light yellow						
hexcolors	[	102	]	=	"#8B4513"	--	saddle brown						
hexcolors	[	103	]	=	"#A0522D"	--	sienna						
hexcolors	[	104	]	=	"#D2691E"	--	chocolate						
hexcolors	[	105	]	=	"#CD853F"	--	peru						
hexcolors	[	106	]	=	"#F4A460"	--	sandy brown						
hexcolors	[	107	]	=	"#DEB887"	--	burly wood						
hexcolors	[	108	]	=	"#D2B48C"	--	tan						
hexcolors	[	109	]	=	"#BC8F8F"	--	rosy brown						
hexcolors	[	110	]	=	"#FFE4B5"	--	moccasin						
hexcolors	[	111	]	=	"#FFDEAD"	--	navajo white						
hexcolors	[	112	]	=	"#FFDAB9"	--	peach puff						
hexcolors	[	113	]	=	"#FFE4E1"	--	misty rose						
hexcolors	[	114	]	=	"#FFF0F5"	--	lavender blush						
hexcolors	[	115	]	=	"#FAF0E6"	--	linen						
hexcolors	[	116	]	=	"#FDF5E6"	--	old lace						
hexcolors	[	117	]	=	"#FFEFD5"	--	papaya whip						
hexcolors	[	118	]	=	"#FFF5EE"	--	sea shell						
hexcolors	[	119	]	=	"#F5FFFA"	--	mint cream						
hexcolors	[	120	]	=	"#708090"	--	slate gray						
hexcolors	[	121	]	=	"#778899"	--	light slate gray						
hexcolors	[	122	]	=	"#B0C4DE"	--	light steel blue						
hexcolors	[	123	]	=	"#E6E6FA"	--	lavender						
hexcolors	[	124	]	=	"#FFFAF0"	--	floral white						
hexcolors	[	125	]	=	"#F0F8FF"	--	alice blue						
hexcolors	[	126	]	=	"#F8F8FF"	--	ghost white						
hexcolors	[	127	]	=	"#F0FFF0"	--	honeydew						
hexcolors	[	128	]	=	"#FFFFF0"	--	ivory						
hexcolors	[	129	]	=	"#F0FFFF"	--	azure						
hexcolors	[	130	]	=	"#FFFAFA"	--	snow						
hexcolors	[	131	]	=	"#000000"	--	black						
hexcolors	[	132	]	=	"#696969"	--	dim gray / dim grey						
hexcolors	[	133	]	=	"#808080"	--	gray / grey						
hexcolors	[	134	]	=	"#A9A9A9"	--	dark gray / dark grey						
hexcolors	[	135	]	=	"#C0C0C0"	--	silver						
hexcolors	[	136	]	=	"#D3D3D3"	--	light gray / light grey						
hexcolors	[	137	]	=	"#DCDCDC"	--	gainsboro						
hexcolors	[	138	]	=	"#F5F5F5"	--	white smoke						
hexcolors	[	139	]	=	"#FFFFFF"	--	white						
hexcolors.	maroon	=	1
hexcolors.	dark_red	=	2
hexcolors.	brown	=	3
hexcolors.	firebrick	=	4
hexcolors.	crimson	=	5
hexcolors.	red	=	6
hexcolors.	tomato	=	7
hexcolors.	coral	=	8
hexcolors.	indian_red	=	9
hexcolors.	light_coral	=	10
hexcolors.	dark_salmon	=	11
hexcolors.	salmon	=	12
hexcolors.	light_salmon	=	13
hexcolors.	orange_red	=	14
hexcolors.	dark_orange	=	15
hexcolors.	orange	=	16
hexcolors.	gold	=	17
hexcolors.	dark_golden_rod	=	18
hexcolors.	golden_rod	=	19
hexcolors.	pale_golden_rod	=	20
hexcolors.	dark_khaki	=	21
hexcolors.	khaki	=	22
hexcolors.	olive	=	23
hexcolors.	yellow	=	24
hexcolors.	yellow_green	=	25
hexcolors.	dark_olive_green	=	26
hexcolors.	olive_drab	=	27
hexcolors.	lawn_green	=	28
hexcolors.	chartreuse	=	29
hexcolors.	green_yellow	=	30
hexcolors.	dark_green	=	31
hexcolors.	green	=	32
hexcolors.	forest_green	=	33
hexcolors.	lime	=	34
hexcolors.	lime_green	=	35
hexcolors.	light_green	=	36
hexcolors.	pale_green	=	37
hexcolors.	dark_sea_green	=	38
hexcolors.	medium_spring_green	=	39
hexcolors.	spring_green	=	40
hexcolors.	sea_green	=	41
hexcolors.	medium_aqua_marine	=	42
hexcolors.	medium_sea_green	=	43
hexcolors.	light_sea_green	=	44
hexcolors.	dark_slate_gray	=	45
hexcolors.	teal	=	46
hexcolors.	dark_cyan	=	47
hexcolors.	aqua	=	48
hexcolors.	cyan	=	49
hexcolors.	light_cyan	=	50
hexcolors.	dark_turquoise	=	51
hexcolors.	turquoise	=	52
hexcolors.	medium_turquoise	=	53
hexcolors.	pale_turquoise	=	54
hexcolors.	aqua_marine	=	55
hexcolors.	powder_blue	=	56
hexcolors.	cadet_blue	=	57
hexcolors.	steel_blue	=	58
hexcolors.	corn_flower_blue	=	59
hexcolors.	deep_sky_blue	=	60
hexcolors.	dodger_blue	=	61
hexcolors.	light_blue	=	62
hexcolors.	sky_blue	=	63
hexcolors.	light_sky_blue	=	64
hexcolors.	midnight_blue	=	65
hexcolors.	navy	=	66
hexcolors.	dark_blue	=	67
hexcolors.	medium_blue	=	68
hexcolors.	blue	=	69
hexcolors.	royal_blue	=	70
hexcolors.	blue_violet	=	71
hexcolors.	indigo	=	72
hexcolors.	dark_slate_blue	=	73
hexcolors.	slate_blue	=	74
hexcolors.	medium_slate_blue	=	75
hexcolors.	medium_purple	=	76
hexcolors.	dark_magenta	=	77
hexcolors.	dark_violet	=	78
hexcolors.	dark_orchid	=	79
hexcolors.	medium_orchid	=	80
hexcolors.	purple	=	81
hexcolors.	thistle	=	82
hexcolors.	plum	=	83
hexcolors.	violet	=	84
hexcolors.	magenta	=	85
hexcolors.	orchid	=	86
hexcolors.	medium_violet_red	=	87
hexcolors.	pale_violet_red	=	88
hexcolors.	deep_pink	=	89
hexcolors.	hot_pink	=	90
hexcolors.	light_pink	=	91
hexcolors.	pink	=	92
hexcolors.	antique_white	=	93
hexcolors.	beige	=	94
hexcolors.	bisque	=	95
hexcolors.	blanched_almond	=	96
hexcolors.	wheat	=	97
hexcolors.	corn_silk	=	98
hexcolors.	lemon_chiffon	=	99
hexcolors.	light_golden_rod_yellow	=	100
hexcolors.	light_yellow	=	101
hexcolors.	saddle_brown	=	102
hexcolors.	sienna	=	103
hexcolors.	chocolate	=	104
hexcolors.	peru	=	105
hexcolors.	sandy_brown	=	106
hexcolors.	burly_wood	=	107
hexcolors.	tan	=	108
hexcolors.	rosy_brown	=	109
hexcolors.	moccasin	=	110
hexcolors.	navajo_white	=	111
hexcolors.	peach_puff	=	112
hexcolors.	misty_rose	=	113
hexcolors.	lavender_blush	=	114
hexcolors.	linen	=	115
hexcolors.	old_lace	=	116
hexcolors.	papaya_whip	=	117
hexcolors.	sea_shell	=	118
hexcolors.	mint_cream	=	119
hexcolors.	slate_gray	=	120
hexcolors.	light_slate_gray	=	121
hexcolors.	light_steel_blue	=	122
hexcolors.	lavender	=	123
hexcolors.	floral_white	=	124
hexcolors.	alice_blue	=	125
hexcolors.	ghost_white	=	126
hexcolors.	honeydew	=	127
hexcolors.	ivory	=	128
hexcolors.	azure	=	129
hexcolors.	snow	=	130
hexcolors.	black	=	131
hexcolors.	dim_gray	=	132
hexcolors.	gray	=	133
hexcolors.	dark_gray	=	134
hexcolors.	silver	=	135
hexcolors.	light_gray	=	136
hexcolors.	gainsboro	=	137
hexcolors.	white_smoke	=	138
hexcolors.	white	=	139

function colorhex(name)
	return '[color='..tostring(hexcolors[hexcolors[name]])..']'
end
function hexToColor(hex, value)
	hex = string.sub(hex,3,#hex)
	return {tonumber(string.sub(hex, 2, 3), 16)/256, tonumber(string.sub(hex, 4, 5), 16)/256, tonumber(string.sub(hex, 6, 7), 16)/256, value or 1}
end
--love.graphics.setColor(0xff, 0x66, 0x00)
return hexcolors